site_name: My Docs

plugins:
  - topic-nav

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand

nav:
  - Home: index.md
  - Developer Environment:
      - developer-environment/index.md
      - Auth:
          - developer-environment/auth/index.md
          - How-To:
              - Python OIDC: developer-environment/auth/how-tos/python-oidc-auth-example.md
      - Kubernetes:
          - developer-environment/kubernetes/index.md
          - Tutorials:
              - Getting Started: developer-environment/kubernetes/tutorials/getting_started.md
  - Software Products:
      - software-products/index.md
      - Athena:
          - software-products/athena/index.md
          - Explanations:
              - software-products/athena/explanations/architecture.md
          - How-Tos:
              - software-products/athena/how-tos/machine-day-testing.md
