site_name: My Docs

plugins:
  - topic-nav
  - monorepo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand

nav:
  - Home: index.md
  - Developer Environment:
      - developer-environment/index.md
      - Auth: '!include ./topics/auth/mkdocs.yml'
      - Kubernetes: '!include ./topics/kubernetes/mkdocs.yml'
  - Software Products:
      - software-products/index.md
      - Athena: '!include ./topics/athena/mkdocs.yml'
