site_name: auth

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand

nav:
  - Home: index.md
  - How-To:
      - Python OIDC: how-tos/python-oidc-auth-example.md
