site_name: kubernetes

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand

nav:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting_started.md
