site_name: My Docs | Athena

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand

nav:
  - Home: index.md
  - Explanations:
      - explanations/architecture.md
  - How-Tos:
      - how-tos/machine-day-testing.md
